services:
  web:
    container_name: levinswap-app
    build: .
    networks:
      - traefik-realt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.levinswap-app.rule=Host(`app.levinswap.realtoken.community`)"
      - "traefik.http.routers.levinswap-app.entrypoints=websecure"
    restart: always

networks:
  traefik-realt:
    external: true
